using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using Avalonia;
using Avalonia.Controls.ApplicationLifetimes;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using Google.GenAI;
using Google.GenAI.Types;

namespace PromptGen.ViewModels;

public partial class MainWindowViewModel : ViewModelBase
{
    // Settings Service
    private readonly Services.SettingsService _settingsService;

    // API Setup
    private string ApiKey => _settingsService.ApiKey; 
    
    private const string ModelId = "gemini-3-flash-preview";

    public MainWindowViewModel()
    {
        _settingsService = new Services.SettingsService();
        LoadSettingsToUI();
    }

    private void LoadSettingsToUI()
    {
        SettingsApiKey = _settingsService.ApiKey;
        SettingsDirectory = string.IsNullOrWhiteSpace(_settingsService.SettingsDirectory) 
            ? AppContext.BaseDirectory 
            : _settingsService.SettingsDirectory;
    }

    [ObservableProperty]
    private string _inputText = string.Empty;

    [ObservableProperty]
    private string _outputText = string.Empty;

    [ObservableProperty]
    private bool _isBusy = false;

    [ObservableProperty]
    private string _statusMessage = "Ready";

    [ObservableProperty]
    private bool _isResultVisible = false;

    [ObservableProperty]
    private bool _hasGeneratedResult = false;

    [ObservableProperty]
    private string _selectedLanguage = "Magyar";

    public List<string> AvailableLanguages { get; } = new List<string>
    {
        "Magyar",
        "English",
        "Deutsch",
        "Français",
        "Español"
    };

    [ObservableProperty]
    private bool _isSettingsVisible = false;

    [ObservableProperty]
    private string _settingsApiKey = string.Empty;

    [ObservableProperty]
    private string _settingsDirectory = string.Empty;

 
    [RelayCommand]
    private async Task GeneratePromptAsync()
    {
        if (string.IsNullOrWhiteSpace(InputText))
        {
            StatusMessage = "Please enter some text first.";
            return;
        }

        if (string.IsNullOrWhiteSpace(ApiKey))
        {
            StatusMessage = "API key not configured. Check settings.";
            return;
        }

        IsBusy = true;
        StatusMessage = "Generating...";
        OutputText = string.Empty;

        try
        {
            System.Environment.SetEnvironmentVariable("GOOGLE_API_KEY", ApiKey);
            
            using var client = new Google.GenAI.Client(); 

            // System instruction in English - only output language changes
            var systemInstruction = $@"**Role:** Expert Prompt Engineer

**Context:** Optimize and structure user inputs for generative language models for maximum efficiency.

**Task:** Analyze the user's unstructured or messy input and rewrite it into a professional, well-structured prompt. The output MUST include these sections: Role, Context, Task, and Format.

**Format:** Provide ONLY the structured prompt without any introductory text or explanations.

**CRITICAL:** Write the generated prompt EXCLUSIVELY in {SelectedLanguage} language!";
            
            var fullPrompt = $"{systemInstruction}\n\nUser Input:\n{InputText}";
            
            // Speed Optimization: Set config for faster & more focused generation
            var config = new GenerateContentConfig
            {
                MaxOutputTokens = 2048,
                Temperature = 0.4f,
                TopP = 0.8f
            };

            // Simplified call - letting the SDK handle its own timeouts
            var response = await client.Models.GenerateContentAsync(
                model: ModelId, 
                contents: fullPrompt,
                config: config
            );

            // Safer access to response text
            var generatedText = response?.Candidates?[0]?.Content?.Parts?[0]?.Text;

            if (!string.IsNullOrEmpty(generatedText))
            {
                OutputText = generatedText;
                StatusMessage = "Done!";
                IsResultVisible = true;
                HasGeneratedResult = true;
            }
            else
            {
                OutputText = "No text was generated by the model.";
                StatusMessage = "Generation failed - empty response.";
            }

        }
        catch (Exception ex)
        {
            OutputText = $"API Error: {ex.Message}\n\n" +
                         $"Details: {ex.InnerException?.Message}\n\n" +
                         $"Stack Trace: {ex.StackTrace}";
            StatusMessage = "Error occurred. Check results.";
            Console.WriteLine($"API Detailed Error: {ex}");
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private void CloseResult()
    {
        IsResultVisible = false;
        StatusMessage = "Ready";
    }

    [RelayCommand]
    private void ViewResult()
    {
        IsResultVisible = true;
    }

    [RelayCommand]
    private async Task CopyToClipboardAsync()
    {
        if (string.IsNullOrWhiteSpace(OutputText)) return;

        if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
        {
             var clipboard = desktop.MainWindow?.Clipboard;
             if (clipboard is not null)
             {
                 await clipboard.SetTextAsync(OutputText);
                 StatusMessage = "Copied to clipboard!";
             }
        }
    }

    [RelayCommand]
    private void OpenSettings()
    {
        IsSettingsVisible = true;
    }

    [RelayCommand]
    private void CloseSettings()
    {
        IsSettingsVisible = false;
    }

    [RelayCommand]
    private void SaveSettings()
    {
        _settingsService.ApiKey = SettingsApiKey;
        StatusMessage = "Settings saved!";
        
        Task.Delay(2000).ContinueWith(_ =>
        {
            StatusMessage = "Ready";
        });
    }

    [RelayCommand]
    private async Task UpdateSettingsDirectory()
    {
        if (Application.Current?.ApplicationLifetime is IClassicDesktopStyleApplicationLifetime desktop)
        {
            var mainWindow = desktop.MainWindow;
            if (mainWindow != null)
            {
                var storageProvider = mainWindow.StorageProvider;
                var result = await storageProvider.OpenFolderPickerAsync(new Avalonia.Platform.Storage.FolderPickerOpenOptions
                {
                    Title = "Select Settings Directory",
                    AllowMultiple = false
                });

                if (result.Count > 0)
                {
                    var selectedPath = result[0].Path.LocalPath;
                    SettingsDirectory = selectedPath;
                    _settingsService.SettingsDirectory = selectedPath;
                    StatusMessage = "Directory updated!";
                }
            }
        }
    }
}
